branches:
  only:
    - master

services:
  - docker

script:
  - make buildfs || exit 1
  - make build || exit 1

after_success:
  - >
    [ "${TRAVIS_BRANCH}" == "master" ] &&
      (docker login --username $DOCKER_USER --password $DOCKER_PASS; \
      docker push ippart/webhook)
